#include "DIO_interface.h"

#ifndef STEPPER_CONFIG_H_
#define STEPPER_CONFIG_H_

#define CTRL_PORT       DIO_u8PORTA

#define STEPPER_BLUE_PIN		DIO_u8PIN0
#define STEPPER_PINK_PIN		DIO_u8PIN1
#define STEPPER_YELLOW_PIN		DIO_u8PIN2
#define STEPPER_ORANGE_PIN		DIO_u8PIN3


#endif /* STEPPER_CONFIG_H_ */
